baseurl         = "https://kelvin-hsu.github.io/personal/"
theme           = "casper-two"
publishDir		= "docs"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "The Transpiring Bayesian"
  subtitle    = "Coming to an understanding in a world of uncertainty"
  copyright   = "© 2018"

  cover       = "img/sunset-tiergarten.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = "kylesmusic"
  githubName = "Kelvin-Hsu"
  linkedinName = "Kelvin-Hsu"
  mediumName = ""

  logo = ""
  orgName = "Kelvin Hsu"
  orgWebsite = "https://Kelvin-Hsu.github.io/personal/"
  orgDescription = ""

  showSupport = true

  author = "Kelvin Hsu"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Sydney, Australia"
  authorWebsite = "https://Kelvin-Hsu.github.io/personal"
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found - Were you looking for something else?"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "CV"
  url = "/files/cv.pdf"
  weight = 100
